column_labels:
  cards:
    id: free
    artist: free
    asciiName: free
    availability: free
    borderColor: free
    cardKingdomFoilId: free
    cardKingdomId: free
    colorIdentity: free
    colorIndicator: free
    colors: free
    convertedManaCost: free
    duelDeck: free
    edhrecRank: free
    faceConvertedManaCost: free
    faceName: free
    flavorName: free
    flavorText: free
    frameEffects: free
    frameVersion: free
    hand: free
    hasAlternativeDeckLimit: free
    hasContentWarning: free
    hasFoil: free
    hasNonFoil: free
    isAlternative: free
    isFullArt: free
    isOnlineOnly: free
    isOversized: free
    isPromo: free
    isReprint: free
    isReserved: free
    isStarter: free
    isStorySpotlight: free
    isTextless: free
    isTimeshifted: free
    keywords: free
    layout: free
    leadershipSkills: free
    life: free
    loyalty: free
    manaCost: free
    mcmId: free
    mcmMetaId: free
    mtgArenaId: free
    mtgjsonV4Id: free
    mtgoFoilId: free
    mtgoId: free
    multiverseId: free
    name: free
    number: free
    originalReleaseDate: free
    originalText: free
    originalType: free
    otherFaceIds: free
    power: free
    printings: free
    promoTypes: free
    purchaseUrls: free
    rarity: free
    scryfallId: free
    scryfallIllustrationId: free
    scryfallOracleId: free
    setCode: free
    side: free
    subtypes: free
    supertypes: free
    tcgplayerProductId: free
    text: free
    toughness: free
    type: free
    types: free
    uuid: free
    variations: free
    watermark: free
  foreign_data:
    id: free
    flavorText: free
    language: free
    multiverseid: free
    name: free
    text: free
    type: free
    uuid: free
  legalities:
    id: free
    format: free
    status: free
    uuid: free
  rulings:
    id: free
    date: free
    text: free
    uuid: free
  set_translations:
    id: free
    language: free
    setCode: free
    translation: free
  sets:
    id: free
    baseSetSize: free
    block: free
    booster: free
    code: free
    isFoilOnly: free
    isForeignOnly: free
    isNonFoilOnly: free
    isOnlineOnly: free
    isPartialPreview: free
    keyruneCode: free
    mcmId: free
    mcmIdExtras: free
    mcmName: free
    mtgoCode: free
    name: free
    parentCode: free
    releaseDate: free
    tcgplayerGroupId: free
    totalSetSize: free
    type: free
annotator: GPT-4o + human_review
review_date: '2026-07-20'
